### ISSUE TITLE
Software

### ISSUE THREAD

**Issue by ctnlaring** [Collinthegeek/arch-installer#4]
more software. Probably have a vertical notebook with categories

**Comment by ctnlaring** [comment]
Started in https://github.com/Collinthegeek/Akita/commit/2f122046c1b65be44af6e62c5ca97d573d81d6af

**Comment by ctnlaring** [comment]
Improved greatly in https://github.com/Collinthegeek/Akita/commit/ab534b64b053aad1fe46202585589c5f03646116

**Comment by Collinthegeek** [comment]
Apps to add:
Synapse
Emacs
Autokey
Libreoffice
Chrome
Pidgin
Hangouts
VLC
Shotwell
Gimp
Spotify
Dropbox
Google Drive
Various torrent clients
tor
wine
virtualbox
nano
More

**Comment by ctnlaring** [comment]
More improvement in https://github.com/Collinthegeek/Akita/commit/4afe4e13243bf5d27275b7d8585619e7cefd9d88

**Comment by ctnlaring** [comment]
done in https://github.com/Collinthegeek/Akita/commit/bb9ba523e7f24d28fcc3abf242175fe97f5d38f8
