### ISSUE TITLE
Come up with a name

### ISSUE THREAD

**Issue by ctnlaring** [Collinthegeek/arch-installer#8]

**Comment by Collinthegeek** [comment]
Some ideas (family tradition of making hostnames characters from Alice in wonderland)

Mock Turtle
Dinah
Mome rath
White knight
Curious Oyster

**Comment by Collinthegeek** [comment]
Maybe some kind of snake to go with python.. but there's already anaconda.. Absolem?

**Comment by ctnlaring** [comment]
I like Akita. Maybe I can come up with some clever arch linux acronym
